version: '3.4'

services:
  sparkflume.eventgenerator:
    image: ${DOCKER_REGISTRY}sparkflumeeventgenerator
    build:
      context: .
      dockerfile: SparkFlume.EventGenerator/Dockerfile

  sparkflume.output:
    image: ${DOCKER_REGISTRY}sparkflumeoutput
    build:
      context: .
      dockerfile: SparkFlume.Output/Dockerfile

  sparkflume.database:
    image: ${DOCKER_REGISTRY}sparkflumedatabase
    build:
      context: .
      dockerfile: SparkFlume.Database/Dockerfile

  sparkflume.flume:
    image: ${DOCKER_REGISTRY}sparkflumeflume
    build:
      context: .
      dockerfile: SparkFlume.Flume/Dockerfile

