version: '3.4'

services:

  sparkflume.database:
    image: ${DOCKER_REGISTRY}sparkflumedatabase
    build:
      context: .
      dockerfile: SparkFlume.Database/Dockerfile

  sparkflume.flume:
    image: ${DOCKER_REGISTRY}sparkflumespark
    depends_on: sparkflumedatabase
    build:
      context: .
      dockerfile: SparkFlume.Flume/Dockerfile

  sparkflume.flume:
    image: ${DOCKER_REGISTRY}sparkflumeflume
    depends_on: sparkflumespark
    build:
      context: .
      dockerfile: SparkFlume.Flume/Dockerfile

  sparkflume.eventgenerator:
    image: ${DOCKER_REGISTRY}sparkflumeeventgenerator
    depends_on: sparkflumeflume
    build:
      context: .
      dockerfile: SparkFlume.EventGenerator/Dockerfile

  sparkflume.output:
    image: ${DOCKER_REGISTRY}sparkflumeoutput
    depends_on: sparkflumedatabase
    build:
      context: .
      dockerfile: SparkFlume.Output/Dockerfile
