version: '3.4'

services:

  sparkflume.database:
    image: ${DOCKER_REGISTRY}sparkflumedatabase
    build:
      context: .
      dockerfile: SparkFlume.Database/Dockerfile

  sparkflume.spark:
    image: ${DOCKER_REGISTRY}sparkflumespark
    depends_on: [ $sparkflume.database ]
    build:
      context: .
      dockerfile: SparkFlume.Flume/Dockerfile

  sparkflume.flume:
    image: ${DOCKER_REGISTRY}sparkflume/flume
    depends_on: [ sparkflume.spark ]
    build:
      context: .
      dockerfile: SparkFlume.Flume/Dockerfile

  sparkflume.eventgenerator:
    image: ${DOCKER_REGISTRY}sparkflumeeventgenerator
    depends_on: [ sparkflume.flume ]
    build:
      context: .
      dockerfile: SparkFlume.EventGenerator/Dockerfile

  sparkflume.output:
    image: ${DOCKER_REGISTRY}sparkflumeoutput
    depends_on: [ sparkflume.database ]
    build:
      context: .
      dockerfile: SparkFlume.Output/Dockerfile
