version: '3.4'

services:

  database:
    build: ./SparkFlume.Database
    ports:
      - "3306:3306"

  spark:
    build: ./SparkFlume.Spark
    depends_on: 
      - database

  flume:
    build: ./SparkFlume.Flume
    depends_on:
      - spark
    ports:
      - "28000:28000"
      - "28001:28001"

  eventgenerator:
    build: ./SparkFlume.EventGenerator
    depends_on:
      - flume

  output:
    build: ./SparkFlume.Output
    depends_on:
      - database
