version: '3.4'

services:

  sparkflume.database:
    image: ${DOCKER_REGISTRY}sparkflume/database
    build:
      context: .
      dockerfile: SparkFlume.Database/Dockerfile

  sparkflume.flume:
    image: ${DOCKER_REGISTRY}sparkflume/spark
    depends_on: [ sparkflumedatabase ]
    build:
      context: .
      dockerfile: SparkFlume.Flume/Dockerfile

  sparkflume.flume:
    image: ${DOCKER_REGISTRY}sparkflume/flume
    depends_on: [ sparkflumespark ]
    build:
      context: .
      dockerfile: SparkFlume.Flume/Dockerfile

  sparkflume.eventgenerator:
    image: ${DOCKER_REGISTRY}sparkflume/eventgenerator
    depends_on: [ sparkflumeflume ]
    build:
      context: .
      dockerfile: SparkFlume.EventGenerator/Dockerfile

  sparkflume.output:
    image: ${DOCKER_REGISTRY}sparkflume/output
    depends_on: [ sparkflumedatabase ]
    build:
      context: .
      dockerfile: SparkFlume.Output/Dockerfile
